# Generated by Django 6.0.4 on 2026-07-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
        ('core', '0005_album_custom_attributes_photo_custom_attributes_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopluginexclusion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_exclusions', to='media.photo'),
        ),
    ]
