# Generated by Django 5.2.4 on 2026-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='photo',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='photo',
            name='hide_location',
            field=models.BooleanField(default=False, help_text='Hide location data from public API'),
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='raw_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='raw_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
