# Generated by Django 6.0.4 on 2026-07-21 17:37

from django.db import migrations


def update_content_types(apps, schema_editor):
    """
    Re-points content types from 'core' to 'media' to preserve 
    permissions and Generic Foreign Keys without creating duplicates.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="core").update(app_label="media")


def drop_initial_media_tables(apps, schema_editor):
    """
    Drops the empty tables created by media.0001_initial so that core_* 
    tables can be cleanly renamed into media_*.
    """
    tables_to_drop = [
        "media_photoinalbum",
        "media_phototag",
        "media_photosize",
        "media_photometadata",
        "media_photo",
        "media_album",
        "media_tag",
        "media_size",
    ]
    with schema_editor.connection.cursor() as cursor:
        for table in tables_to_drop:
            cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_album_custom_attributes_photo_custom_attributes_and_more'),
        ('media', '0001_initial'),
        ('integration', '0002_alter_photopluginexclusion_photo'),
    ]

    operations = [
        # Step 1: Clear auto-populated sizes in media & update ContentTypes
        migrations.RunPython(
            update_content_types,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 2: Swap the physical tables and clear 'core' from Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_initial_media_tables,
                    reverse_code=migrations.RunPython.noop,
                ),
                migrations.AlterModelTable(name='Size', table='media_size'),
                migrations.AlterModelTable(name='Tag', table='media_tag'),
                migrations.AlterModelTable(name='Album', table='media_album'),
                migrations.AlterModelTable(name='Photo', table='media_photo'),
                migrations.AlterModelTable(name='PhotoMetadata', table='media_photometadata'),
                migrations.AlterModelTable(name='PhotoSize', table='media_photosize'),
                migrations.AlterModelTable(name='PhotoTag', table='media_phototag'),
                migrations.AlterModelTable(name='PhotoInAlbum', table='media_photoinalbum'),
            ],
            state_operations=[
                migrations.RemoveField(model_name='photoinalbum', name='album'),
                migrations.RemoveField(model_name='photo', name='tags'),
                migrations.RemoveField(model_name='phototag', name='photo'),
                migrations.RemoveField(model_name='photoinalbum', name='photo'),
                migrations.RemoveField(model_name='photosize', name='photo'),
                migrations.RemoveField(model_name='photometadata', name='photo'),
                migrations.AlterUniqueTogether(name='photoinalbum', unique_together=None),
                migrations.AlterUniqueTogether(name='photosize', unique_together=None),
                migrations.RemoveField(model_name='photosize', name='size'),
                migrations.AlterUniqueTogether(name='phototag', unique_together=None),
                migrations.RemoveField(model_name='phototag', name='tag'),
                migrations.DeleteModel(name='Album'),
                migrations.DeleteModel(name='PhotoInAlbum'),
                migrations.DeleteModel(name='Photo'),
                migrations.DeleteModel(name='PhotoMetadata'),
                migrations.DeleteModel(name='PhotoSize'),
                migrations.DeleteModel(name='Size'),
                migrations.DeleteModel(name='PhotoTag'),
                migrations.DeleteModel(name='Tag'),
            ],
        ),
    ]