# Generated by Django 6.0.4 on 2026-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='write_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='admin_access',
            field=models.BooleanField(default=False, help_text='Grants access to the Admin API'),
        ),
    ]
