# Generated by Django 6.0.4 on 2026-07-21 17:20

import django.db.models.deletion
import django.utils.timezone
import media.models
import uuid
from django.db import migrations, models
from media import UI_THUMBNAIL_LARGE, UI_THUMBNAIL_SMALL


def create_builtin_sizes(apps, schema_editor):
    Size = apps.get_model('media', 'Size')
    Size.objects.create(
        slug='original',
        comment="Original, unprocessed image",
        max_dimension=2147483647,
        square_crop=False,
        builtin=True,
        can_edit=False,
        public=False,
    )

    Size.objects.create(
        slug=UI_THUMBNAIL_LARGE,
        comment="Photo & album detail pages",
        max_dimension=512,
        square_crop=False,
        builtin=True,
        can_edit=True,
        public=False,
    )

    Size.objects.create(
        slug=UI_THUMBNAIL_SMALL,
        comment="Compact preview",
        max_dimension=128,
        square_crop=True,
        builtin=True,
        can_edit=True,
        public=False,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=4096)),
                ('raw_image', models.ImageField(upload_to=media.models.Photo.get_image_file_path)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('hidden', models.BooleanField(default=False, help_text='Hide from public API')),
                ('_published', models.BooleanField(db_column='published', default=False)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hide_location', models.BooleanField(default=False, help_text='Hide location data from public API')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('max_dimension', models.PositiveIntegerField()),
                ('square_crop', models.BooleanField(default=False)),
                ('builtin', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True, help_text='Allow in the public API?')),
            ],
            options={
                'ordering': ['max_dimension'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=4096)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_method', models.CharField(choices=[('CREATED', 'Photo Created Date (Exif)'), ('PUBLISHED', 'Publish Date'), ('MANUAL', 'Manual'), ('RANDOM', 'Random')], default='PUBLISHED', max_length=10)),
                ('sort_descending', models.BooleanField(default=True)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='media.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.photo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='_photos',
            field=models.ManyToManyField(related_name='albums', through='media.PhotoInAlbum', to='media.photo', verbose_name='Photos'),
        ),
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=255, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('focal_length_35mm', models.FloatField(blank=True, null=True)),
                ('aperture', models.FloatField(blank=True, null=True)),
                ('shutter_speed', models.FloatField(blank=True, null=True)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('exposure_program', models.CharField(blank=True, max_length=255, null=True)),
                ('exposure_compensation', models.FloatField(blank=True, null=True)),
                ('flash', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=512, null=True)),
                ('raw_latitude', models.FloatField(blank=True, null=True)),
                ('raw_longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='media.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.tag')),
            ],
            options={
                'ordering': ['tag__name'],
                'unique_together': {('photo', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', through='media.PhotoTag', to='media.tag'),
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=media.models.PhotoSize.get_image_file_path)),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='media.photo')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media.size')),
            ],
            options={
                'ordering': ['size__max_dimension'],
                'unique_together': {('photo', 'size')},
            },
        ),
        migrations.RunPython(create_builtin_sizes, reverse_code=migrations.RunPython.noop),
    ]
