# Generated by Django 6.0.4 on 2026-07-24 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_channel(apps, schema_editor):
    Channel = apps.get_model('media', 'Channel')
    ChannelPhoto = apps.get_model('media', 'ChannelPhoto')
    Photo = apps.get_model('media', 'Photo')

    default_channel = Channel.objects.create(
        name = "Default",
        description = "The default publishing channel",
        include_new_photos = True,
        builtin = True
    )

    channel_photos = []

    for photo in Photo.objects.filter(canonical_hidden=False):
        channel_photos.append(
            ChannelPhoto(
                channel=default_channel,
                photo=photo,
                publish_date=photo.canonical_publish_date,
                published=photo._published,
            )
        )

    ChannelPhoto.objects.bulk_create(channel_photos, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('include_new_photos', models.BooleanField(default=True, help_text='Include new photos by default')),
                ('builtin', models.BooleanField(default=False, help_text='Cannot delete or modify this channel')),
            ],
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='hidden',
            new_name='canonical_hidden',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='publish_date',
            new_name='canonical_publish_date',
        ),
        migrations.AlterField(
            model_name='photo',
            name='canonical_hidden',
            field=models.BooleanField(
                default=False,
                help_text='Default hidden state',
            ),
        ),
        migrations.AlterField(
            model_name='photo',
            name='canonical_publish_date',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text='Default publish date',
            ),
        ),
        migrations.AlterField(
            model_name='photo',
            name='hide_location',
            field=models.BooleanField(default=False, help_text='Hide location data from the public'),
        ),
        migrations.AlterField(
            model_name='size',
            name='public',
            field=models.BooleanField(default=True, help_text='Allow public use?'),
        ),
        migrations.CreateModel(
            name='ChannelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Publish date')),
                ('published', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media.channel')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='media.photo')),
            ],
        ),
        migrations.RunPython(create_default_channel, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='photo',
            name='_published',
        )
    ]
