"""
Django settings for photoserv project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from .version import __version__ as APP_VERSION
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- ENV settings
SECRET_KEY = os.environ.get("APP_KEY")
DEBUG = (os.environ.get("DEBUG_MODE", "false").strip().lower() == "true")
IS_CONTAINER = os.environ.get("PHOTOSERV_IS_CONTAINER", "false").lower().strip() == "true"

# --- Application definition

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS","127.0.0.1").split(",") if not DEBUG else ["*"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

INSTALLED_APPS = [
    "core",
    "api_key",
    "public_rest_api",
    "iam",
    "job_overview",
    "integration",
    "errorhtml",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django_tables2",
    "crispy_forms",
    "crispy_daisyui",

    "rest_framework",
    "drf_spectacular",

    'mozilla_django_oidc',

    "django_celery_results",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
    "photoserv.middleware.LoginRequiredMiddleware",
]

ROOT_URLCONF = 'photoserv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'photoserv.context.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'photoserv.wsgi.application'

# Templating Plugin Config
DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "table table-zebra",
}

# Crispy Forms Config
CRISPY_ALLOWED_TEMPLATE_PACKS = "daisyui"
CRISPY_TEMPLATE_PACK = "daisyui"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_USER = os.getenv("DATABASE_USER", "photoserv")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD", "photoserv")
DATABASE_NAME = os.getenv("DATABASE_NAME", "photoserv")
DATABASE_HOST = os.getenv("DATABASE_HOST", "database")
DATABASE_PORT = int(os.getenv("DATABASE_PORT", "5432"))
DB_ENGINE = os.getenv("DATABASE_ENGINE", "postgres")

DB_CONFIG_MAP = {
    "postgres": {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': os.getenv('DATABASE_NAME', DATABASE_NAME),
         'USER': os.getenv('DATABASE_USERNAME', DATABASE_USER),
         'PASSWORD': os.getenv('DATABASE_PASSWORD', DATABASE_PASSWORD),
         'HOST': os.getenv('DATABASE_HOST', DATABASE_HOST),
         'PORT': os.getenv('DATABASE_PORT', DATABASE_PORT),
     },

    "sqlite": {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR if not IS_CONTAINER else "/database") + '/db.sqlite3',
    }
}

if DB_ENGINE not in DB_CONFIG_MAP.keys():
    raise ValueError("DATABASE_ENGINE must be in " + str(list(DB_CONFIG_MAP.keys())))

DATABASES = {
    'default': DB_CONFIG_MAP[DB_ENGINE]
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# --- Celery Configuration ---
REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_ALWAYS_EAGER = DEBUG
CELERY_TASK_TIME_LIMIT = 60 * 60
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 604800

# --- Cache Configuration (use Redis for shared cache across workers) ---
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/0',
    }
}


CELERY_BEAT_SCHEDULE = {
    'run-consistency': {
        'task': 'core.tasks.consistency',
        'schedule': 60.0 * 60 * 2,
    },
    'publish-photos': {
        'task': 'core.tasks.publish_photos',
        'schedule': 60.0 * 10 if not DEBUG else 30.0,
    },
    'integration-consistency': {
        'task': 'integration.tasks.consistency',
        'schedule': 60.0 * 60 * 24,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = '/static/'
STATICFILES_DIRS = ('static',)

# Uploads

if IS_CONTAINER:
    MEDIA_ROOT = '/content'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'content')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- REST Framework Configuration ---

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'api_key.permissions.HasAPIKey'
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',  # Only JSON, no HTML
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Photoserv API',
    'DESCRIPTION': 'Public API for your Photoserv instance.',
    'VERSION': APP_VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [],
    'EXTENSIONS_TO_SCHEMA_FUNCTION': lambda generator, request, public: {
        'x-speakeasy-retries': {
            'strategy': 'backoff',
            'backoff': {
                'initialInterval': 500,
                'maxInterval': 60000,
                'maxElapsedTime': 3600000,
                'exponent': 1.5,
            },
            'statusCodes': ['5XX'],
            'retryConnectionErrors': True,
        }
    }
}

# --- IAM Config

AUTH_USER_MODEL = "iam.User"
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

SIMPLE_AUTH = (os.environ.get("SIMPLE_AUTH", "false").lower().strip() == "true")

OIDC_NAME = os.environ.get("OIDC_NAME", "Single Sign On")
OIDC_RP_CLIENT_ID = os.environ.get("OIDC_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = os.environ.get("OIDC_CLIENT_SECRET")

OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get("OIDC_AUTHORIZATION_ENDPOINT")
OIDC_OP_TOKEN_ENDPOINT = os.environ.get("OIDC_TOKEN_ENDPOINT")
OIDC_OP_USER_ENDPOINT = os.environ.get("OIDC_USER_ENDPOINT")
OIDC_OP_JWKS_ENDPOINT = os.environ.get("OIDC_JWKS_ENDPOINT")
OIDC_RP_SIGN_ALGO = os.environ.get("OIDC_SIGN_ALGO", "RS256")
OIDC_RP_SCOPES = "openid email profile"

OIDC_ENABLED = all([
    OIDC_RP_CLIENT_ID,
    OIDC_RP_CLIENT_SECRET,
    OIDC_OP_AUTHORIZATION_ENDPOINT,
    OIDC_OP_TOKEN_ENDPOINT,
    OIDC_OP_USER_ENDPOINT,
    OIDC_OP_JWKS_ENDPOINT,
])

AUTH_ENABLED = SIMPLE_AUTH or OIDC_ENABLED

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'iam.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# ------- Integrations

INTEGRATION_QUEUE_DELAY = 60 * 10  # 10 minutes

# Python plugins path
PLUGINS_PATH = Path(os.getenv("PLUGINS_PATH", str(Path("/plugins") if IS_CONTAINER else BASE_DIR / "plugins")))
